# name: Deploy
# on:
#   push:
#     branches:
#       - main
#       - develop
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to VPS
#         uses: appleboy/ssh-action@v1
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             export PATH="/root/.nvm/versions/node/v24.13.1/bin:$PATH"
#             if [ "${{ github.ref_name }}" = "main" ]; then
#               cd /var/www/acab/backend-prod
#               git checkout -- .
#               git pull origin main
#               yarn install --frozen-lockfile
#               npx prisma migrate deploy
#               npx prisma generate
#               yarn build
#               pm2 restart acab-backend-prod
#             else
#               cd /var/www/acab/backend-staging
#               git checkout -- .
#               git pull origin develop
#               yarn install --frozen-lockfile
#               npx prisma migrate deploy
#               npx prisma generate
#               yarn build
#               pm2 restart acab-backend-staging
#             fi